# Generated by Django 2.2.11 on 2020-04-04 13:43

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('clocking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClockTypes',
            new_name='ClockType',
        ),
    ]
