# Generated by Django 2.2.11 on 2020-04-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocking', '0002_auto_20200404_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='valid_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
